### ISSUE TITLE
Some questions about transferring scRNA-seq data into hyperbolic space

### ISSUE THREAD

**Issue by HelloWorldLTY** [RonenTalmonLab/HyperbolicProcrustesAnalysis#1]
Hello, I am the listener in NeuriPS who is interested in the application of HPA in scRNA-seq data. I tried to use the code here to process scRNA-seq data but got this error:
<img width="943" alt="image" src="https://user-images.githubusercontent.com/43333475/145832011-75826942-7d5e-46a4-ad64-6bdf66855289.png">
Could you please give me any hints? Thanks.

**Comment by RonenTalmonLab** [comment]
Hi, thanks for your interest in our work. 

By the error message, it looks as if the problem is unrelated to our code, but to the code that generates the hyperbolic embedding at the link the https://github.com/facebookresearch/poincare-embeddings


Our code gets the hyperbolic embedding as input, so before running our code you should make sure that you can generate the hyperbolic embedding of your scRNA data.
Even though it is not our code, we suspect that the problem you are having is related to the fact that your data format does not match the input expected by the dataloader of the poincare-embedding, in which the input to the dataloader (from your error message) should be pairs of nodes ('id1','id2') and the weights of the edges connecting them ('weight').

**Comment by HelloWorldLTY** [comment]
Hi, thanks for your reply, it really helps me a lot. My last question is which graph structure you used for generating the embeddings? KNN graph with id1, id2 as cells or other structures? Thanks a lot!
